leftnav:
- identifier: b720ccca-c722-3beb-0eab-c7efa1b4d3aa
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: b0fe1210-1db8-6bf6-b9d4-fadbe6513fc4
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: be202549-32a0-d784-d83a-0f872710ab14
  name: This Course at MIT
  url: /pages/this-course-at-mit
  weight: 30
- identifier: 69ab796e-382c-86b5-a9ed-f1115712f8a5
  name: Readings
  url: /pages/readings
  weight: 40
- identifier: 47104115-6cc7-bc25-61ea-e5b8d8ed77fc
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 50
- identifier: c18a0843-3319-98dc-7d4e-ce0494a435c0
  name: Discussion
  url: /pages/discussion
  weight: 60
- identifier: 49ff76a4-e228-4a96-3d49-7a74f2c705a4
  name: Assignments
  url: /pages/assignments
  weight: 70
- identifier: efc9dc48-fbef-f622-86c3-c3ed860f9792
  name: Projects
  url: /pages/projects
  weight: 80
